#   ╭────────────────────── Notice ── Notice ── Notice ──────────────────────╮
#   │                                                                        │
#   │                          Do not edit this file.                        │
#   │                                                                        │
#   │      THIS FILE IS AUTOMATICALLY REGENERATED UPON EVERY RELEASE.        │
#   │                                                                        │
#   ╰────────────────────── Notice ── Notice ── Notice ──────────────────────╯
#
# The values in this file are inserted automatically when new release are made.
# Manual edits will be lost.  Please see the Makefile in the project directory.

__name__        = 'sidetrack'
__version__     = '1.1.0'
__description__ = 'Simple debug tracing package for Python'
__url__         = 'https://github.com/caltechlibrary/sidetrack'
__author__      = 'Michael Hucka'
__email__       = 'mhucka@caltech.edu'
__license__     = 'BSD 3-clause'
